# Generated by Django 3.0.2 on 2020-08-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('quest', models.CharField(max_length=30)),
                ('quest2', models.CharField(max_length=30)),
            ],
        ),
    ]
