# Generated by Django 3.0.2 on 2020-08-27 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='quest',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='quest2',
            new_name='choice',
        ),
    ]
